version: "3.9"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.7
    container_name: chat-meili
    ports:
      - "7700:7700"                    # API
    environment:
      MEILI_ENV: development
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: meili_master   # Đổi khi lên prod!
    volumes:
      - meili_data:/meili_data         # dữ liệu bền

volumes:
  meili_data:
